### ISSUE TITLE
All RU (relative usage) values are 1

### ISSUE THREAD

**Issue by mattheiter** [gxiaolab/mountainClimber#7]
Running the recommended workflow with STAR, all RU values end up being 1 using custom data. Implementing the transcriptome re-alignment in addition to the genome alignment unfortunately didn't change things.

Investigating the source code, I found that the reason for RU's being 1 is that there is only always a single segment:

https://github.com/gxiaolab/mountainClimber/blob/65132f210d17e5313198e4a0f83f737e57de6b53/src/mountainClimberRU.py#L234

Any ideas on how to fix that?

**Comment by mattheiter** [comment]
Setting the param `--winsize` of mountainclimberCP to a lower value (e.g. `10`) seems to help but that leads to other issues, namely:

```
Traceback (most recent call last):
  File "/mountainClimberCP.py", line 1396, in <module>
    main(sys.argv[1:])
  File "/mountainClimberCP.py", line 1113, in main
    peak_inds_ttest_opt = param2cpopt[(denoise_winsize_opt, amp_thresh_opt, peak_min_dist_opt)].tolist()
KeyError: (10, 0.15, 50)
```
